@extends(config('sentinel.views.layout','sentinel::layout'))
@section('content')<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1">{{ $target->name ?? ('User #'.$target->getKey()) }}</h1><div class="text-muted">Moderation profile</div></div><span class="badge fs-6 {{ $riskScore >= 70 ? 'text-bg-danger' : ($riskScore >= 40 ? 'text-bg-warning' : 'text-bg-success') }}">Risk {{ $riskScore }}/100</span></div>
<div class="row g-4"><div class="col-xl-8"><div class="card border-0 shadow-sm mb-4"><div class="card-header bg-transparent fw-semibold">Enforcement history</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Action</th><th>Status</th><th>Reason</th><th>Date</th></tr></thead><tbody>@forelse($actions as $action)<tr><td>{{ $action->type->value }}</td><td>{{ $action->status->value }}</td><td>{{ $action->reason }}</td><td>{{ $action->created_at }}</td></tr>@empty<tr><td colspan="4" class="text-muted">No Sentinel actions.</td></tr>@endforelse</tbody></table></div></div>
<div class="card border-0 shadow-sm"><div class="card-header bg-transparent fw-semibold">Cases & reports</div><div class="card-body"><p><strong>{{ $cases->count() }}</strong> recent cases · <strong>{{ $reports->count() }}</strong> recent reports · <strong>{{ $watchlist->count() }}</strong> active watchlist entries</p></div></div></div>
<div class="col-xl-4"><div class="card border-0 shadow-sm mb-3"><div class="card-body"><h2 class="h6">Warn</h2><form method="POST" action="{{ route('sentinel.users.warn',$target) }}">@csrf<input name="reason" class="form-control mb-2" placeholder="Reason" required><select name="severity" class="form-select mb-2"><option>medium</option><option>low</option><option>high</option></select><button class="btn btn-warning w-100">Issue warning</button></form></div></div>
<div class="card border-0 shadow-sm mb-3"><div class="card-body"><h2 class="h6">Strike</h2><form method="POST" action="{{ route('sentinel.users.strike',$target) }}">@csrf<input name="reason" class="form-control mb-2" placeholder="Reason" required><input name="points" type="number" min="1" value="1" class="form-control mb-2"><input name="category" value="other" class="form-control mb-2"><button class="btn btn-danger w-100">Issue strike</button></form></div></div>
<div class="card border-0 shadow-sm mb-3"><div class="card-body"><h2 class="h6">Ban</h2><form method="POST" action="{{ route('sentinel.users.ban',$target) }}">@csrf<input name="reason" class="form-control mb-2" placeholder="Reason" required><input name="days" type="number" min="1" class="form-control mb-2" placeholder="Days (blank = permanent)"><button class="btn btn-danger w-100">Ban account</button></form></div></div>
<div class="card border-0 shadow-sm mb-3"><div class="card-body"><h2 class="h6">Restriction</h2><form method="POST" action="{{ route('sentinel.users.restrict',$target) }}">@csrf<input name="reason" class="form-control mb-2" placeholder="Reason" required><select name="restriction" class="form-select mb-2"><option value="posting">Posting</option><option value="read_only">Read only</option><option value="login">Login</option><option value="shadow">Shadow</option></select><input name="hours" type="number" class="form-control mb-2" placeholder="Hours (blank = permanent)"><button class="btn btn-outline-danger w-100">Restrict</button></form></div></div>
<div class="card border-0 shadow-sm mb-3"><div class="card-body"><h2 class="h6">Watchlist</h2><form method="POST" action="{{ route('sentinel.users.watch',$target) }}">@csrf<input name="reason" class="form-control mb-2" placeholder="Reason" required><select name="severity" class="form-select mb-2"><option>medium</option><option>low</option><option>high</option><option>critical</option></select><button class="btn btn-outline-warning w-100">Add to watchlist</button></form></div></div>
<div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h6">Masquerade</h2><form method="POST" action="{{ route('sentinel.users.masquerade',$target) }}">@csrf<input name="reason" class="form-control mb-2" placeholder="Support reason" required><button class="btn btn-outline-primary w-100">Masquerade as user</button></form></div></div></div></div>@endsection
